apiVersion: spv.no/v2alpha1
kind: AzureKeyVaultSecret
metadata:
  name: mediawiki-db-type
spec:
  vault:
    name: {{ .Values.azureKeyVault.name }}
    object:
      name: mediawiki-db-type
      type: secret
  output:
    secret:
      name: mediawiki-db-type-secret
---
apiVersion: spv.no/v2alpha1
kind: AzureKeyVaultSecret
metadata:
  name: mediawiki-db-host
spec:
  vault:
    name: {{ .Values.azureKeyVault.name }}
    object:
      name: mediawiki-db-host
      type: secret
  output:
    secret:
      name: mediawiki-db-host-secret
---
apiVersion: spv.no/v2alpha1
kind: AzureKeyVaultSecret
metadata:
  name: mediawiki-db-name
spec:
  vault:
    name: {{ .Values.azureKeyVault.name }}
    object:
      name: mediawiki-db-name
      type: secret
  output:
    secret:
      name: mediawiki-db-name-secret
---
apiVersion: spv.no/v2alpha1
kind: AzureKeyVaultSecret
metadata:
  name: mediawiki-db-user
spec:
  vault:
    name: {{ .Values.azureKeyVault.name }}
    object:
      name: mediawiki-db-user
      type: secret
  output:
    secret:
      name: mediawiki-db-user-secret
---
apiVersion: spv.no/v2alpha1
kind: AzureKeyVaultSecret
metadata:
  name: mediawiki-db-password
spec:
  vault:
    name: {{ .Values.azureKeyVault.name }}
    object:
      name: mediawiki-db-password
      type: secret
  output:
    secret:
      name: mediawiki-db-password-secret
