apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mediawiki
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: mediawiki
    spec:
      containers:
        - name: mediawiki
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 80
          env:
            - name: MEDIAWIKI_DB_HOST
              value: {{ .Values.db.host }}
            - name: MEDIAWIKI_DB_NAME
              value: {{ .Values.db.name }}
            - name: MEDIAWIKI_DB_USER
              valueFrom:
                secretKeyRef:
                  name: mediawiki-db-secret
                  key: username
            - name: MEDIAWIKI_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mediawiki-db-secret
                  key: password
          readinessProbe:
            httpGet:
              path: /index.php
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /index.php
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
