apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mediawiki-app-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mediawiki-app
  template:
    metadata:
      labels:
        app: mediawiki-app
    spec:
      containers:
        - name: mediawiki-app-container
          image: {{ .Values.mediawikiApp.image.repository }}:{{ .Values.mediawikiApp.image.tag }}
          imagePullPolicy: {{ .Values.mediawikiApp.image.pullPolicy }}
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: {{ .Values.mediawikiApp.resources.limits.cpu }}
              memory: {{ .Values.mediawikiApp.resources.limits.memory }}
            requests:
              cpu: {{ .Values.mediawikiApp.resources.requests.cpu }}
              memory: {{ .Values.mediawikiApp.resources.requests.memory }}
          livenessProbe:
            httpGet:
              path: {{ .Values.mediawikiApp.livenessProbe.httpGet.path }}
              port: {{ .Values.mediawikiApp.livenessProbe.httpGet.port }}
            initialDelaySeconds: {{ .Values.mediawikiApp.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.mediawikiApp.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.mediawikiApp.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.mediawikiApp.livenessProbe.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.mediawikiApp.readinessProbe.httpGet.path }}
              port: {{ .Values.mediawikiApp.readinessProbe.httpGet.port }}
            initialDelaySeconds: {{ .Values.mediawikiApp.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.mediawikiApp.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.mediawikiApp.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.mediawikiApp.readinessProbe.failureThreshold }}
