apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 1Gi   # Adjust storage size as needed
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /path/to/host/directory   # Replace with your host path
  persistentVolumeReclaimPolicy: Retain
