apiVersion: spv.no/v2alpha1
kind: AzureKeyVaultSecret
metadata:
  name: mysql-root-password
spec:
  vault:
    name: {{ .Values.azureKeyVault.name }}
    object:
      name: mysql-root-password
      type: secret
  output:
    secret:
      name: mysql-root-password-secret
---
apiVersion: spv.no/v2alpha1
kind: AzureKeyVaultSecret
metadata:
  name: mysql-database
spec:
  vault:
    name: {{ .Values.azureKeyVault.name }}
    object:
      name: mysql-database
      type: secret
  output:
    secret:
      name: mysql-database-secret
---
apiVersion: spv.no/v2alpha1
kind: AzureKeyVaultSecret
metadata:
  name: mysql-user
spec:
  vault:
    name: {{ .Values.azureKeyVault.name }}
    object:
      name: mysql-user
      type: secret
  output:
    secret:
      name: mysql-user-secret
---
apiVersion: spv.no/v2alpha1
kind: AzureKeyVaultSecret
metadata:
  name: mysql-password
spec:
  vault:
    name: {{ .Values.azureKeyVault.name }}
    object:
      name: mysql-password
      type: secret
  output:
    secret:
      name: mysql-password-secret
